use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'Example' do
  
  pod 'CaamDau/All', :path => '../../../'
  pod 'Router', :path => '../../Module/Router/'
  pod 'Utility', :path => '../../Module/Utility/'
  pod 'Map', :path => '../../Module/Map/'
  pod 'Demo', :path => '../../Module/Demo/'
  pod 'TabBarNavigation', :path => '../../Module/TabBarNavigation/'
  
end
