use_frameworks!

target 'CD_Example' do
  pod 'CD', :path => '../'

  target 'CD_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
