use_frameworks!
inhibit_all_warnings!
platform :ios, '10.0'

#install! 'cocoapods', generate_multiple_pod_projects: true, :incremental_installation => true

source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do
  pod 'CaamDau/All', :path => '../'
  pod 'Sign', :path => './Module/Sign'
  pod 'TabBarNavigation', :path => './Module/TabBarNavigation'
  pod 'Utility', :path => './Module/Utility'
  pod 'Router', :path => './Module/Router'
  pod 'Home', :path => './Module/Home'
  pod 'Mine', :path => './Module/Mine'
  pod 'Demo', :path => './Module/Demo'
  # pod 'Map/Location', :path => './Module/Map'
  # pod 'Map/Baidu', :path => './Module/Map'
  pod 'BaiduMapKit', '5.1.0'
  pod 'BMKLocationKit'
  pod 'BaiduTraceKit-Lite'
  # ---------- Debug 调试工具 ----------
  # 虽然Swift 设置了在Release 不导入 Debugging，
  # 但还是建议 Debugging 调试面板在正式上线时删除，不要带到线上。
  # 因为有一些hook操作会可能污染线上代码。
  pod 'Debugging', :path => './Module/Debugging/', :configurations => ['Debug']
  
end
