use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'Example' do
  
  pod 'CD/All', :path => '~/Desktop/MyWorking/CDKit/CD/'
  pod 'Util', :path => '~/Desktop/MyWorking/CDKit/CD/Example/Util/'
  pod 'Web', :path => '~/Desktop/MyWorking/CDKit/CD/Example/Modul/'
  pod 'Sign', :path => '~/Desktop/MyWorking/CDKit/CD/Example/Modul/'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  # 阿里七巧板
  pod 'Tangram'
  # 阿里协程库
  #pod 'coobjc'
  pod 'Then', '~> 2.4.0'
  pod 'Toast-Swift', '~> 4.0.1'
  pod 'KeychainAccess'
  pod 'Hero'
end
