use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'Example' do
  
  pod 'CaamDau/All', :path => '../../../../'
  pod 'Util', :path => '../../../Util/'
  pod 'Publish', :path => '../../'
  
end
