use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'Example' do
  
  pod 'CaamDau/All', :path => '../../../'
  pod 'Home', :path => '../../Module/Home/'
  pod 'Router', :path => '../../Module/Router/'
  pod 'Utility', :path => '../../Module/Utility/'
  
  #pod 'RxSwift'
  #pod 'RxCocoa'
  #pod 'RxDataSources'
  # 阿里七巧板
  #pod 'Tangram'
  # 阿里协程库
  #pod 'coobjc'
  #pod 'Then', '~> 2.4.0'
  #pod 'Toast-Swift', '~> 4.0.1'
  #pod 'KeychainAccess'
  #pod 'Hero'
  #pod "SkeletonView"
  
  # ---------- Debug 调试工具 ----------
  # 虽然Swift 设置了在Release 不导入 Debugging，
  # 但还是建议 Debugging 调试面板在正式上线时删除，不要带到线上。
  # 因为有一些hook操作会可能污染线上代码。
  #pod 'Debugging', :path => '../../Module/Debugging/', :configurations => ['Debug']
end
