use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'Example' do

  pod 'CaamDau/All', :path => '../../../../'
  pod 'Util', :path => '../../../Util/'
  pod 'Home', :path => '../../'

  #pod 'RxSwift'
  #pod 'RxCocoa'
  #pod 'RxDataSources'
  #pod 'Alamofire', '4.8.2'
  #pod 'Cache', '5.2.0'
  #pod 'SwiftyJSON', '4.3.0'
  #pod 'CleanJSON'
  # 阿里七巧板
  #pod 'Tangram'
  # 阿里协程库
  #pod 'coobjc'
  
end
