use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'Example' do
  
  
  
  pod 'CD/All', :path => '~/Desktop/MyWorking/CDKit/CD/'
  pod 'Util', :path => '~/Desktop/MyWorking/CDKit/CD/Example/Util/'
  pod 'ThirdSDK', :path => '~/Desktop/MyWorking/CDKit/CD/Example/ThirdSDK/'
  
  #pod 'RxSwift'
  #pod 'RxCocoa'
  #pod 'RxDataSources'
  pod 'Alamofire', '4.8.2'
  pod 'Cache', '5.2.0'
  pod 'SwiftyJSON', '4.3.0'
  pod 'CleanJSON'
  # 阿里七巧板
  #pod 'Tangram'
  # 阿里协程库
  #pod 'coobjc'
  
end
